name: git2mail release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

env:
  GITHUB_REF: "${{ github.ref }}"

jobs:
  build:
    strategy:
      matrix:
        build: [linux, macos, windows]
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            cargo_arg: --release
          - build: macos
            os: macos-latest
            cargo_arg: --release
          - build: windows
            os: windows-latest
            target: x86_64-pc-windows-msvc
            cargo_arg: --release
            extension: .exe

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
    - name: Set target if any
      if: matrix.target
      run: rustup target add ${{ matrix.target }}
    - name: If target is musl, install musl-tools (including musl-gcc)
      if: matrix.target == 'x86_64-unknown-linux-musl'
      run: |
        sudo apt update
        sudo apt install musl-tools -y
    - name: Build
      run: cargo build ${{ matrix.cargo_arg }} --all-features --package git2mail --verbose ${{ matrix.target && format('--target {0}', matrix.target) || '' }}
    - name: Prepare binary path
      id: binary_path
      shell: bash
      run: |
        if [ -n "${{ matrix.target }}" ]; then
          echo "path=./target/${{ matrix.target }}/release/git2mail${{ matrix.extension || '' }}" >> $GITHUB_OUTPUT
        else
          echo "path=./target/release/git2mail${{ matrix.extension || '' }}" >> $GITHUB_OUTPUT
        fi
    - name: Upload resulting 'git2mail'
      uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
      with:
        name: git2mail-${{ matrix.build }}
        path: ${{ steps.binary_path.outputs.path }}

  release:
    name: GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Query version number
        id: get_version
        shell: bash
        run: |
          echo "using version tag ${GITHUB_REF:15}"
          echo "version=${GITHUB_REF:15}" >> $GITHUB_OUTPUT
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@32aa5b4c155d76c94e4ec883a223c947b2f02656 # v2.2.3
        with:
          path: CHANGELOG.md
      - name: Download Linux artifact
        uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
        with:
          name: git2mail-linux
          path: linux

      - name: Download macOS artifact
        uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
        with:
          name: git2mail-macos
          path: macos

      - name: Download Windows artifact
        uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
        with:
          name: git2mail-windows
          path: windows

      - name: Rename artifacts
        shell: bash
        run: |
          mv linux/git2mail git2mail-linux-static-${{ steps.get_version.outputs.version }}
          mv macos/git2mail git2mail-macos-${{ steps.get_version.outputs.version }}
          mv windows/git2mail.exe git2mail-windows-${{ steps.get_version.outputs.version }}.exe

      - name: Create Release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: git2mail-${{ steps.get_version.outputs.version }}
          name: git2mail-${{ steps.get_version.outputs.version }}
          body: ${{ steps.changelog_reader.outputs.changes }}
          draft: true
          files: |
            git2mail-linux-static-${{ steps.get_version.outputs.version }}
            git2mail-macos-${{ steps.get_version.outputs.version }}
            git2mail-windows-${{ steps.get_version.outputs.version }}.exe
